# Generated by Django 2.2.6 on 2020-10-29 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.CharField(blank=True, max_length=100, null=True)),
                ('pic', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('pics', models.CharField(blank=True, max_length=100, null=True)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moments.wechatuser')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(to='moments.wechatuser', on_delete=django.db.models.deletion.CASCADE)),
                ('user2', models.ForeignKey(to='moments.wechatuser', on_delete=django.db.models.deletion.CASCADE)),
                ('friendship_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FriendshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(to='moments.wechatuser', related_name='friendship_requests_sent', on_delete=django.db.models.deletion.CASCADE)),
                ('to_user', models.ForeignKey(to='moments.wechatuser', related_name='friendship_requests_received', on_delete=django.db.models.deletion.CASCADE)),
                ('pending', models.CharField(default='pending', max_length=15)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
